### Multi get from index products
POST http://localhost:9200/products/_mget
Content-Type: application/json

{
    "ids": ["1", "2"]
}

### Multi get from index orders
POST http://localhost:9200/orders/_mget
Content-Type: application/json

{
    "ids": ["1", "2"]
}

### Multi get from index customers
POST http://localhost:9200/customers/_mget
Content-Type: application/json

{
    "ids": ["1", "2"]
}

### Multi get from multiple indexes
POST http://localhost:9200/_mget
Content-Type: application/json

{
    "docs": [
        {
            "_index": "products",
            "_id": "1"
        },
        {
            "_index": "orders",
            "_id": "1"
        },
        {
            "_index": "customers",
            "_id": "1"
        },
        {
            "_index": "customers",
            "_id": "2"
        }
    ]
}